# Cargo.toml
[workspace]
members = [
    "infat-lib",
    "infat-cli",
]
resolver = "2"

[workspace.dependencies]
# CLI and config
clap = { version = "4.5", features = ["derive"] }
toml = "0.8"
eyre = "0.6"
color-eyre = "0.6"

# Logging
tracing = "0.1"
